name: "Issue Labeler"
on:
  issues:
    types: [opened, reopened]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      # v2.4
    - uses: github/issue-labeler@829a8bf1b184f74cc575b5435093a92c7b846983
      with:
        repo-token: "${{ secrets.PROJECT_MANAGER_TOKEN }}"
        configuration-path: .github/labeler.yml
        enable-versioned-regex: 0
